namespace CentaurScores.Api.Contracts;

public sealed record ApiError(string Code, string Message);
public sealed record LoginRequest(string Username, string Password, Guid TenantId);
public sealed record CreateTenantRequest(string Name, string? LogoUrl, Guid? ParentTenantId);
public sealed record UpdateAccountRequest(string Username, string? Password, string? DisplayName, string? Email, string? Authorization);
public sealed record UpdateProfileRequest(string? DisplayName, string? Email);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public sealed record CreateCategoryRequest(string Name);
public sealed record UpdateCategoryRequest(string Name);
public sealed record CreateCategoryValueRequest(int ValueId, string Name);
public sealed record UpdateCategoryValueRequest(string Name);
public sealed record CreateParticipantListRequest(string Name, bool IsActive);
public sealed record CreateParticipantRequest(string LastName, string FullName, string? FederationNumber, Dictionary<Guid, int> Categories, bool IsActive = true);
public sealed record CreateTemplateRequest(string Name, Guid? ParticipantListId, bool AllowFreeParticipants = true, string DeviceSelectionMode = "list-and-free", string ConfigurationJson = "");
public sealed record CreateMatchRequest(string Name, DateOnly Date, string? ShortCode, bool IsOpen, Guid? ParticipantListId, string DeviceSelectionMode, int Ends, int ArrowsPerEnd, int? GroupEnds, bool AllowFreeParticipants = true, string KeyboardJson = "", string ScoringRulesJson = "[]");
public sealed record CreateMatchParticipantRequest(Guid? ParticipantListMemberId, string LastName, string FullName, string? FederationNumber, Dictionary<Guid, int> Categories);
public sealed record EnterScoreRequest(int End, int Arrow, string KeyId, int Value);
public sealed record CreateDeviceRequest(string Name);
public sealed record AssignParticipantDeviceRequest(Guid? DeviceId);
public sealed record ReorderDevicesRequest(List<Guid> DeviceIds);
public sealed record ReorderDeviceParticipantsRequest(List<Guid> ParticipantIds);
public sealed record CreateScopeRequest(string Scope, List<Guid> GroupByCategoryIds, bool IncludeAverage, bool IncludeGroupScores, bool IncludeEqualizers, bool IncludePersonalBest);
public sealed record LiveScoringMatch(Guid Id, DateOnly Date, string Name);
public sealed record LiveScoringEntry(int Position, bool NeedsTieBreaker, string Line1, string? Line2, string? Line3, double? Average, int Arrows, int Score);
public sealed record LiveScoringBlock(string Name, IReadOnlyList<LiveScoringEntry> Entries);
public sealed record LiveScoringPage(int Timeout, string? Logo, string Tenant, string MatchName, DateOnly MatchDate, IReadOnlyList<LiveScoringBlock> Blocks);
public sealed record ScorekeeperCategoryValue(int Id, string Name);
public sealed record ScorekeeperCategory(Guid Id, string Name, IReadOnlyList<ScorekeeperCategoryValue> Values);
public sealed record ScorekeeperKey(string Id, string Label, int Value, string Color);
public sealed record ScorekeeperParticipantCategory(Guid Id, string Name, string? Value);
public sealed record ScorekeeperMatchParticipant(string? FederationNumber, string Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory> Categories, Guid MatchParticipantId, Guid? TenantParticipantId, IReadOnlyList<string>? AvailableKeyIDs, IReadOnlyList<string?> ArrowScores);
public sealed record ScorekeeperMatch(string Device, string Match, int Ends, int ArrowsPerEnd, int? GroupEnds, IReadOnlyList<ScorekeeperCategory> Categories, bool AllowModifyParticipants, bool AllowCustomParticipants, IReadOnlyList<ScorekeeperKey> Keyboard, IReadOnlyList<ScorekeeperMatchParticipant> Participants);
public sealed record ScorekeeperParticipantInfo(Guid? MatchParticipantId, Guid? TenantParticipantId, string? FederationNumber, string Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory> Categories);
public sealed record ScorekeeperParticipantOptions(IReadOnlyList<ScorekeeperParticipantInfo> Unassigned, IReadOnlyList<ScorekeeperParticipantInfo> Assigned, IReadOnlyList<ScorekeeperParticipantInfo> Potential);
public sealed record ScorekeeperParticipantRequest(Guid? MatchParticipantId, Guid? TenantParticipantId, string? FederationNumber, string? Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory>? Categories, IReadOnlyList<string>? AvailableKeyIDs, IReadOnlyList<string?>? ArrowScores);
public sealed record ScorekeeperScoreUpdate(int Index, string? Old, string? New);
public sealed record ScorekeeperScoreUpdates(Guid MatchParticipantId, IReadOnlyList<ScorekeeperScoreUpdate> Updates);
public sealed record ScorekeeperScoreConflict(int Index, string? Current, string? Old, string? New);
public sealed record ScorekeeperScoreUpdateResult(Guid MatchParticipantId, string Error, IReadOnlyList<ScorekeeperScoreConflict> Conflicts);
public sealed record ScorekeeperTime(DateTimeOffset Time);
public sealed record CreateCompetitionRequest(string Name, DateOnly StartDate, DateOnly EndDate, List<Guid> GroupByCategoryIds);
public sealed record CreateRoundRequest(int Order, string ShortName, string LongName);
public sealed record UpdateRoundRequest(string ShortName, string LongName);
public sealed record ReorderRoundsRequest(List<Guid> RoundIds);
public sealed record AssignMatchRequest(Guid MatchId);
public sealed record CreateCompetitionRuleRequest(string Name, List<Guid> RoundIds, int HighestScores, int MinimumScores, string Aggregation);
public sealed record UpdateCompetitionRuleRequest(string Name, List<Guid> RoundIds, int HighestScores, int MinimumScores, string Aggregation);
public sealed record ReorderCompetitionRulesRequest(List<Guid> RuleIds);
public sealed record CompetitionResultScore(int Value, bool Used);
public sealed record CompetitionResultEntry(string? Position, bool NeedsTieBreaker, string Name, bool Disqualified, int? Total, IReadOnlyDictionary<Guid, CompetitionResultScore> RoundScores, IReadOnlyDictionary<string, int> RuleScores);
public sealed record CompetitionResultGroup(string Name, IReadOnlyList<CompetitionResultEntry> Entries);
public sealed record CompetitionResultRound(Guid Id, string ShortName, string LongName, int Order);
public sealed record CompetitionResultsDocument(string CompetitionName, DateOnly StartDate, DateOnly EndDate, IReadOnlyList<CompetitionResultRound> Rounds, IReadOnlyList<CompetitionResultGroup> Groups);