using CentaurScores.Api.Domain;

namespace CentaurScores.Api.Contracts;

public sealed record ApiError(string Code, string Message);
public sealed record LoginRequest(string Username, string Password);
public sealed record SelectTenantRequest(Guid TenantId);
public sealed record TenantAccessView(Guid TenantId, string TenantName, string? LogoUrl, string Authorization);
public sealed record CreateTenantRequest(string Name, string? LogoUrl, Guid? ParentTenantId, string? DefaultNarrowcastScope = null);
public sealed record UpdateDefaultNarrowcastScopeRequest(string? DefaultNarrowcastScope);
public sealed record DefaultScopeSettings(string? TenantValue, string EffectiveValue);
public sealed record ScopeConflictSummary(Guid TenantId, string TenantName, string Scope, int MatchCount);
public sealed record UpdateAccountRequest(string Username, string? Password, string? DisplayName, string? Email, string? Authorization);
public sealed record UpdateProfileRequest(string? DisplayName, string? Email);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public sealed record CreateCategoryRequest(string Name);
public sealed record UpdateCategoryRequest(string Name);
public sealed record CreateCategoryValueRequest(int ValueId, string Name);
public sealed record UpdateCategoryValueRequest(string Name);
public sealed record CreateParticipantListRequest(string Name, bool IsActive);
public sealed record CreateParticipantRequest(string LastName, string FullName, string? FederationNumber, Dictionary<Guid, int> Categories, bool IsActive = true);
public sealed record ImportParticipantListResult(int Created, int Updated, IReadOnlyList<string> Warnings);
public sealed record ParticipantListSummary(Guid Id, Guid TenantId, string Name, bool IsActive, int MemberCount, int ActiveMemberCount);
public sealed record CreateTemplateRequest(string Name, Guid? ParticipantListId, bool AllowFreeParticipants = true, string DeviceSelectionMode = "list-and-free", string ConfigurationJson = "", string? PersonalBestClassifier = null);
public sealed record CreateMatchRequest(string Name, DateOnly Date, string? ShortCode, bool IsOpen, Guid? ParticipantListId, string DeviceSelectionMode, int Ends, int ArrowsPerEnd, int? GroupEnds, bool AllowFreeParticipants = true, string KeyboardJson = "", string ScoringRulesJson = "[]", string? PersonalBestClassifier = null);
public sealed record MatchListItem(Guid Id, Guid TenantId, string Name, DateOnly Date, string? ShortCode, bool IsOpen, Guid? ParticipantListId, string DeviceSelectionMode, int Ends, int ArrowsPerEnd, int? GroupEnds, bool AllowFreeParticipants, string KeyboardJson, string ScoringRulesJson, int ParticipantCount, int UnlistedParticipantCount, IReadOnlyList<LiveScoreScope> LiveScopes);
public sealed record CreateMatchParticipantRequest(Guid? ParticipantListMemberId, string LastName, string FullName, string? FederationNumber, Dictionary<Guid, int> Categories);
public sealed record EnterScoreRequest(int End, int Arrow, string KeyId, int Value);
public sealed record CreateDeviceRequest(string Name);
public sealed record AssignParticipantDeviceRequest(Guid? DeviceId);
public sealed record ReorderDevicesRequest(List<Guid> DeviceIds);
public sealed record ReorderDeviceParticipantsRequest(List<Guid> ParticipantIds);
public sealed record CreateScopeRequest(string Scope, List<Guid> GroupByCategoryIds, bool IncludeAverage, bool IncludeGroupScores, bool IncludeEqualizers, bool IncludePersonalBest);
public sealed record LiveScoringMatch(Guid Id, DateOnly Date, string Name);
public sealed record LiveScoringEntry(int Position, bool NeedsTieBreaker, string Line1, string? Line2, double? Average, int Arrows, int Score, bool AboveTarget = false);
public sealed record LiveScoringBlock(string Name, IReadOnlyList<LiveScoringEntry> Entries);
public sealed record LiveScoringPage(int Timeout, string? Logo, string Tenant, string MatchName, DateOnly MatchDate, int Ends, int ArrowsPerEnd, int? GroupEnds, IReadOnlyList<LiveScoringBlock> Blocks);
public sealed record ScorekeeperCategoryValue(int Id, string Name);
public sealed record ScorekeeperCategory(Guid Id, string Name, IReadOnlyList<ScorekeeperCategoryValue> Values);
public sealed record ScorekeeperKey(string Id, string Label, int Value, string Color);
public sealed record ScorekeeperParticipantCategory(Guid Id, string Name, string? Value);
public sealed record ScorekeeperMatchParticipant(string? FederationNumber, string Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory> Categories, Guid MatchParticipantId, Guid? TenantParticipantId, IReadOnlyList<string>? AvailableKeyIDs, IReadOnlyList<string?> ArrowScores);
public sealed record ScorekeeperMatch(string Device, string Match, int Ends, int ArrowsPerEnd, int? GroupEnds, IReadOnlyList<ScorekeeperCategory> Categories, bool AllowModifyParticipants, bool AllowCustomParticipants, IReadOnlyList<ScorekeeperKey> Keyboard, IReadOnlyList<ScorekeeperMatchParticipant> Participants);
public sealed record ScorekeeperParticipantInfo(Guid? MatchParticipantId, Guid? TenantParticipantId, string? FederationNumber, string Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory> Categories);
public sealed record ScorekeeperParticipantOptions(IReadOnlyList<ScorekeeperParticipantInfo> Unassigned, IReadOnlyList<ScorekeeperParticipantInfo> Assigned, IReadOnlyList<ScorekeeperParticipantInfo> Potential);
public sealed record ScorekeeperParticipantRequest(Guid? MatchParticipantId, Guid? TenantParticipantId, string? FederationNumber, string? Name, string? Info, IReadOnlyList<ScorekeeperParticipantCategory>? Categories, IReadOnlyList<string>? AvailableKeyIDs, IReadOnlyList<string?>? ArrowScores);
public sealed record ScorekeeperScoreUpdate(int Index, string? Old, string? New);
public sealed record ScorekeeperScoreUpdates(Guid MatchParticipantId, IReadOnlyList<ScorekeeperScoreUpdate> Updates);
public sealed record ScorekeeperScoreConflict(int Index, string? Current, string? Old, string? New);
public sealed record ScorekeeperScoreUpdateResult(Guid MatchParticipantId, string Error, IReadOnlyList<ScorekeeperScoreConflict> Conflicts);
public sealed record ScorekeeperTime(DateTimeOffset Time);
public sealed record CreateCompetitionRequest(string Name, DateOnly StartDate, DateOnly EndDate, List<Guid> GroupByCategoryIds);
public sealed record CreateRoundRequest(int Order, string ShortName, string LongName);
public sealed record UpdateRoundRequest(string ShortName, string LongName);
public sealed record ReorderRoundsRequest(List<Guid> RoundIds);
public sealed record AssignMatchRequest(Guid MatchId);
public sealed record CreateCompetitionRuleRequest(string Name, List<Guid> RoundIds, int HighestScores, int MinimumScores, string Aggregation);
public sealed record UpdateCompetitionRuleRequest(string Name, List<Guid> RoundIds, int HighestScores, int MinimumScores, string Aggregation);
public sealed record ReorderCompetitionRulesRequest(List<Guid> RuleIds);
public sealed record CompetitionResultScore(int Value, bool Used);
public sealed record CompetitionResultEntry(string? Position, bool NeedsTieBreaker, string Name, bool Disqualified, int? Total, IReadOnlyDictionary<Guid, CompetitionResultScore> RoundScores, IReadOnlyDictionary<string, int> RuleScores);
public sealed record CompetitionResultGroup(string Name, IReadOnlyList<CompetitionResultEntry> Entries);
public sealed record CompetitionResultRound(Guid Id, string ShortName, string LongName, int Order);
public sealed record CompetitionResultsDocument(string CompetitionName, DateOnly StartDate, DateOnly EndDate, IReadOnlyList<CompetitionResultRound> Rounds, IReadOnlyList<CompetitionResultGroup> Groups);

// Backup and restore
public sealed record CreateBackupRequest(bool IncludeSubTenants);
public sealed record RestoreBackupResult(Guid NewTenantId, string NewTenantName, IReadOnlyList<string> Warnings);

// Personal Best tracking
public sealed record PersonalBestStatus(bool Enabled, bool OwnedHere, Guid? OwningTenantId);
public sealed record SavePersonalBestClassifiersRequest(List<string> Classifiers);
public sealed record PersonalBestDisciplineValueRef(Guid TenantId, Guid CategoryId, int ValueId);
public sealed record SavePersonalBestDisciplineRequest(Guid? Id, string Name, List<PersonalBestDisciplineValueRef> Values);
public sealed record SavePersonalBestDisciplinesRequest(List<SavePersonalBestDisciplineRequest> Disciplines);
public sealed record PersonalBestDisciplineValueView(Guid TenantId, string TenantName, Guid CategoryId, string CategoryName, int ValueId, string ValueName);
public sealed record PersonalBestDisciplineView(Guid Id, string Name, IReadOnlyList<PersonalBestDisciplineValueView> Values);
public sealed record PersonalBestAvailableValue(Guid TenantId, string TenantName, Guid CategoryId, string CategoryName, int ValueId, string ValueName, Guid? TakenByDisciplineId);
public sealed record SavePersonalBestExportColumnRequest(string ColumnName, string Field, string? DateFormat);
public sealed record SavePersonalBestExportConfigRequest(string ExportMode, string TableName, List<SavePersonalBestExportColumnRequest> Columns);
public sealed record PersonalBestExportColumnView(string ColumnName, string Field, string? DateFormat);
public sealed record PersonalBestExportConfigView(string ExportMode, string TableName, IReadOnlyList<PersonalBestExportColumnView> Columns);
public sealed record SavePersonalBestImportConfigRequest(string TableName, string DateColumn, string FederationNumberColumn, string NameColumn, string DisciplineColumn, string MatchClassifierColumn, string ScoreColumn, string UpdateDateColumn);
public sealed record PersonalBestImportConflictView(string FederationNumber, string Discipline, string MatchClassifier, string ConflictType, bool Actionable);
public sealed record PersonalBestImportResult(int NewArchers, int NewRegistrations, IReadOnlyList<string> Warnings, Guid? BatchId, IReadOnlyList<PersonalBestImportConflictView> Conflicts);
public sealed record PersonalBestConflictResolution(string FederationNumber, string Discipline, string MatchClassifier, string Action);
public sealed record ResolvePersonalBestConflictsRequest(List<PersonalBestConflictResolution> Resolutions);
public sealed record PersonalBestLogRow(string FederationNumber, string Name, string Discipline, string MatchClassifier, DateOnly Date, int Score);