// <auto-generated />
using System;
using CentaurScores.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentaurScores.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821084333_WidenTenantLogoUrl")]
    partial class WidenTenantLogoUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CentaurScores.Api.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Authorization")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("authorization");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_tenant_id_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ArrowScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Arrow")
                        .HasColumnType("int")
                        .HasColumnName("arrow");

                    b.Property<int>("End")
                        .HasColumnType("int")
                        .HasColumnName("end");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("key_id");

                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("match_participant_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_arrow_scores");

                    b.HasIndex("MatchParticipantId")
                        .HasDatabaseName("ix_arrow_scores_match_participant_id");

                    b.ToTable("arrow_scores", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CategoryValue", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<int>("ValueId")
                        .HasColumnType("int")
                        .HasColumnName("value_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("CategoryId", "ValueId")
                        .HasName("pk_category_values");

                    b.HasIndex("CategoryId", "ValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_values_category_id_value_id");

                    b.ToTable("category_values", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GroupByCategoryIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("group_by_category_ids_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("competition_id");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("long_name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("short_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_rounds");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_competition_rounds_competition_id");

                    b.ToTable("competition_rounds", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionRoundMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionRoundId")
                        .HasColumnType("char(36)")
                        .HasColumnName("competition_round_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_round_matches");

                    b.HasIndex("CompetitionRoundId")
                        .HasDatabaseName("ix_competition_round_matches_competition_round_id");

                    b.ToTable("competition_round_matches", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionScoreRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Aggregation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("aggregation");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("competition_id");

                    b.Property<int>("HighestScores")
                        .HasColumnType("int")
                        .HasColumnName("highest_scores");

                    b.Property<int>("MinimumScores")
                        .HasColumnType("int")
                        .HasColumnName("minimum_scores");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("RoundIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("round_ids_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_score_rules");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_competition_score_rules_competition_id");

                    b.ToTable("competition_score_rules", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.LiveScoreScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("GroupByCategoryIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("group_by_category_ids_json");

                    b.Property<bool>("IncludeAverage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("include_average");

                    b.Property<bool>("IncludeEqualizers")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("include_equalizers");

                    b.Property<bool>("IncludeGroupScores")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("include_group_scores");

                    b.Property<bool>("IncludePersonalBest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("include_personal_best");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scope");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_live_score_scopes");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_live_score_scopes_match_id");

                    b.ToTable("live_score_scopes", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("AllowFreeParticipants")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_free_participants");

                    b.Property<int>("ArrowsPerEnd")
                        .HasColumnType("int")
                        .HasColumnName("arrows_per_end");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Ends")
                        .HasColumnType("int")
                        .HasColumnName("ends");

                    b.Property<int?>("GroupEnds")
                        .HasColumnType("int")
                        .HasColumnName("group_ends");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_open");

                    b.Property<string>("KeyboardJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("keyboard_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("ScoringRulesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scoring_rules_json");

                    b.Property<string>("ShortCode")
                        .HasColumnType("longtext")
                        .HasColumnName("short_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categories");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("device_id");

                    b.Property<string>("FederationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("federation_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<Guid?>("ParticipantListMemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("participant_list_member_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_match_participants");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_participants_match_id");

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.MatchTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("configuration_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParticipantListId")
                        .HasColumnType("char(36)")
                        .HasColumnName("participant_list_id");

                    b.Property<string>("ParticipantSelectionMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("participant_selection_mode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_match_templates");

                    b.ToTable("match_templates", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ParticipantList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_participant_lists");

                    b.ToTable("participant_lists", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ParticipantListMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categories");

                    b.Property<string>("FederationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("federation_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<Guid>("ParticipantListId")
                        .HasColumnType("char(36)")
                        .HasColumnName("participant_list_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_participant_list_members");

                    b.HasIndex("ParticipantListId")
                        .HasDatabaseName("ix_participant_list_members_participant_list_id");

                    b.ToTable("participant_list_members", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ScoreDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("ParticipantOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("participant_order_json");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("selection_mode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_score_devices");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_score_devices_match_id");

                    b.ToTable("score_devices", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ArrowScore", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.MatchParticipant", null)
                        .WithMany("Scores")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arrow_scores_match_participants_match_participant_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CategoryValue", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Category", null)
                        .WithMany("Values")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_values_categories_category_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionRound", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Competition", null)
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_rounds_competitions_competition_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionRoundMatch", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.CompetitionRound", null)
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_round_matches_competition_rounds_competition_rou");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionScoreRule", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Competition", null)
                        .WithMany("ScoringRules")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_score_rules_competitions_competition_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.LiveScoreScope", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Match", null)
                        .WithMany("LiveScopes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_live_score_scopes_matches_match_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.MatchParticipant", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_matches_match_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ParticipantListMember", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.ParticipantList", null)
                        .WithMany("Members")
                        .HasForeignKey("ParticipantListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participant_list_members_participant_lists_participant_list_");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ScoreDevice", b =>
                {
                    b.HasOne("CentaurScores.Api.Domain.Match", null)
                        .WithMany("Devices")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_devices_matches_match_id");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Category", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Competition", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("ScoringRules");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.CompetitionRound", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.Match", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("LiveScopes");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.MatchParticipant", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("CentaurScores.Api.Domain.ParticipantList", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
