import type { Language } from './types'

export const labels = {
  en: { home: 'Overview', matches: 'Matches', competitions: 'Competitions', participants: 'Participants', categories: 'Categories', templates: 'Templates', accounts: 'Accounts', open: 'Open now', upcoming: 'Coming up', login: 'Sign in to manage your tenant', signIn: 'Sign in', logout: 'Log out', manage: 'Manage tenant data', add: 'Add', profile: 'Profile', profileDetails: 'Profile details', profileDetailsHint: 'Update your real name and e-mail address.', displayName: 'Display name', email: 'E-mail', save: 'Save', password: 'Password', changePassword: 'Change password', changePasswordHint: 'Enter your current password to set a new one.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', profileSaved: 'Profile details saved.', passwordSaved: 'Password changed.', passwordMismatch: 'New password and confirmation do not match.', currentPasswordWrong: 'Current password is incorrect.', tenants: 'Sub-tenants', tenantsHint: 'Manage sub-tenants of this tenant.', tenantName: 'Name', tenantLogo: 'Logo', tenantLogoHint: 'SVG or PNG, 1:1 aspect ratio preferred, 256KB maximum.', tenantLogoAspectWarning: 'This image is not close to the preferred 2:1 aspect ratio.', tenantSaved: 'Sub-tenant saved.', deleteTenant: 'Delete sub-tenant', deleteTenantConfirm: 'This permanently deletes {name} and all of its data. This cannot be undone. Continue?', newTenant: 'New sub-tenant' },
  nl: { home: 'Overzicht', matches: 'Wedstrijden', competitions: 'Competities', participants: 'Schutters', categories: 'Categorieën', templates: 'Sjablonen', accounts: 'Accounts', open: 'Nu open', upcoming: 'Binnenkort', login: 'Meld je aan om je tenant te beheren', signIn: 'Aanmelden', logout: 'Afmelden', manage: 'Tenantgegevens beheren', add: 'Toevoegen', profile: 'Profiel', profileDetails: 'Profielgegevens', profileDetailsHint: 'Werk je naam en e-mailadres bij.', displayName: 'Weergavenaam', email: 'E-mail', save: 'Opslaan', password: 'Wachtwoord', changePassword: 'Wachtwoord wijzigen', changePasswordHint: 'Vul je huidige wachtwoord in om een nieuw wachtwoord in te stellen.', currentPassword: 'Huidig wachtwoord', newPassword: 'Nieuw wachtwoord', confirmPassword: 'Bevestig nieuw wachtwoord', profileSaved: 'Profielgegevens opgeslagen.', passwordSaved: 'Wachtwoord gewijzigd.', passwordMismatch: 'Nieuw wachtwoord en bevestiging komen niet overeen.', currentPasswordWrong: 'Huidig wachtwoord is onjuist.', tenants: 'Sub-tenants', tenantsHint: 'Beheer sub-tenants van deze tenant.', tenantName: 'Naam', tenantLogo: 'Logo', tenantLogoHint: 'SVG of PNG, bij voorkeur 1:1 beeldverhouding, maximaal 256KB.', tenantLogoAspectWarning: 'Deze afbeelding wijkt af van de voorkeursverhouding 2:1.', tenantSaved: 'Sub-tenant opgeslagen.', deleteTenant: 'Sub-tenant verwijderen', deleteTenantConfirm: 'Dit verwijdert {name} en alle bijbehorende data definitief. Dit kan niet ongedaan worden gemaakt. Doorgaan?', newTenant: 'Nieuwe sub-tenant' }
} satisfies Record<Language, Record<string, string>>

export function translationsFor(language: Language) {
  return labels[language]
}
